"use client";

import { Roboto } from "next/font/google";
import "./globals.css";
import Navebar from "./_Components/Header/Navebar/navebar";
import { ClerkProvider } from "@clerk/nextjs";
import Cart_Context from "./_Components/_Context/cart_context.js";
import { useEffect, useState } from "react";
import Footer from "./_Components/Footer/footer.jsx";
import { usePathname } from "next/navigation";

const inter = Roboto({ subsets: ["latin"], weight: "700" });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  useEffect(() => {
    document.title = "EcoBanner";
  }, []);

  const [cart, setCart] = useState([]);
  const pathname = usePathname();
  const homePage = pathname.includes("Pages") || pathname.includes("auth");

  return (
    <ClerkProvider>
      <Cart_Context.Provider value={[cart, setCart]}>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Navebar />
            {!homePage && <Footer />}
          </body>
        </html>
      </Cart_Context.Provider>
    </ClerkProvider>
  );
}
